# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, 13.4
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MoonMeet' do
  config = use_native_modules!

#   pod 'GoogleUtilities', :modular_headers => true
#   pod 'FirebaseCore', :modular_headers => true
#   pod 'FirebaseCoreExtension', :modular_headers => true
#   pod 'FirebaseFirestoreInternal', :modular_headers => true
#   pod 'FirebaseInstallations', :modular_headers => true
#   pod 'GoogleDataTransport', :modular_headers => true
#   pod 'FirebaseABTesting', :modular_headers => true
#   pod 'FirebaseAppCheckInterop', :modular_headers => true
#   pod 'FirebaseAuthInterop', :modular_headers => true
#   pod 'nanopb', :modular_headers => true

  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )



  target 'MoonMeetTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    installer.pods_project.build_configurations.each do |config|
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
  end
end
