name: Android CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/android.yml'
      - 'android/**'
      - 'src/**'
      - 'yarn.lock'
      - 'package.json'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/android.yml'
      - 'android/**'
      - 'src/**'
      - 'yarn.lock'
      - 'package.json'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Install node_modules
      run: yarn install --frozen-lockfile
    - name: Decode Google Service JSON File.
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $GOOGLE_SERVICES_JSON > android/app/google-services.json
    - name: Decode Sensitive JS File
      env:
        SENSITIVE_JS: ${{ secrets.SENSITIVE_JS }}
      run: echo $SENSITIVE_JS > src/sensitive.js
    - name: Increase Gradle JVM max memory
      run: sed -i 's/Xmx896/Xmx4096/g' android/gradle.properties && sed -i 's/256m/1024m/g' android/gradle.properties
    - name: Clean the build.
      run: cd android && ./gradlew clean && cd .. 
    - name: List gradle tasks (testing tasks)
      run: cd android && ./gradlew tasks && cd ..
    - name: Build debug APK (testing the build)
      env:
        KEYPASS: ${{ secrets.KEYSTORE_PASSWORD }}
        KEYALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        KEYALIASPASS: ${{ secrets.KEY_ALIAS_PASSWORD }}
      run: cd android && ./gradlew assembleDebug && cd ..
    - name: Build release APK.
      env:
        KEYPASS: ${{ secrets.KEYSTORE_PASSWORD }}
        KEYALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        KEYALIASPASS: ${{ secrets.KEY_ALIAS_PASSWORD }}
      run: cd android && ./gradlew assembleRelease && cd ..
