name: Android CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/android.yml'
      - 'android/**'
      - 'yarn.lock'
      - 'example/yarn.lock'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/android.yml'
      - 'android/**'
      - 'yarn.lock'
      - 'example/yarn.lock'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Restore node_modules from cache
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install node_modules
      run: yarn install --frozen-lockfile
    - name: Restore Gradle cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Setup secrets
      run: export keystorePass=${{ secrets.KEYSTORE_PASSWORD }} && export keystoreAlias=${{ secrets.KEYSTORE_ALIAS }} && export keystoreAliasPass=${{ secrets.KEY_ALIAS_PASSWORD }}
    - name: Decode Google Service JSON File.
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $GOOGLE_SERVICES_JSON > android/app/google-services.json
    - name: Decode Sensitive JS File
      env:
        SENSITIVE_JS: ${{ secrets.SENSITIVE_JS }}
      run: echo $SENSITIVE_JS > src/sensitive.js
    - name: Run Gradle Build for android/
      run: cd android && ./gradlew assembleRelease --build-cache --no-daemon && cd ..
